### ISSUE TITLE
Use workdir for wps outputs

### ISSUE THREAD

**Issue by cehbrecht** [c3s-magic/c3s-magic-wps#80]
## Description

WPS output generation is not consistently using `workdir`. I have temporally fixed it in my branch for the `rainfarm` process:
https://github.com/cehbrecht/c3s-magic-wps/blob/d4f5c3e0d7b35c611e8dbf56e98c4f1c584a1e33/c3s_magic_wps/processes/wps_rainfarm.py#L221

It looks like this happens only for the zip archive? So the rest of the outputs (pictures etc) might be ok.

When `workdir`is not used, files are written to the folder from which the WPS service was started. In production environment this is read-only:

```
[Errno 13] Permission denied: 'rainfarm_result.zip'
```

## Environment

* c3s-magic-wps version used, if any:
* Python version, if any:
* Operating System:

**Comment by nielsdrost** [comment]
You are right, we're fixing this in all metrics.
