### ISSUE TITLE
Provide a post_install.sh script

### ISSUE THREAD

**Issue by cehbrecht** [c3s-magic/c3s-magic-wps#82]
## Description

There are several manual installation steps which should be automated in a bash script. This script can be used by the Ansible installation and Dockerfile.

## Environment

* c3s-magic-wps version used, if any:
* Python version, if any:
* Operating System:

## Additional Information

See also:
https://github.com/c3s-magic/climexp_numerical_wps/issues/5

**Comment by nielsdrost** [comment]
We are fixing this with #84 , as the conda package already runs all the needed steps.

**Comment by nielsdrost** [comment]
#84 merged, assume this is fixed now.
