### ISSUE TITLE
Julia didn't work for rainfarm

### ISSUE THREAD

**Issue by cehbrecht** [c3s-magic/c3s-magic-wps#83]
## Description

I have installed julia as described in the `Dockerfile` but the `rainfarm` process still has issues:
```
Julia version 1.0.3 at location /usr/local/src/julia-1.0.3/bin will be used.
Loading setup script for JuliaCall...
Finish loading setup script for JuliaCall.
Error: Error happens in Julia.
ArgumentError: Package RainFARM not found in current path:
- Run `import Pkg; Pkg.add("RainFARM")` to install the RainFARM package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:823
 [2] eval(::Module, ::Any) at ./boot.jl:319
 [3] eval_string(::String) at /usr/local/Miniconda3-4.5.12-Linux-x86_64/envs/c3s-magic/lib/R/library/JuliaCall/julia/setup.jl:195
 [4] docall(::Ptr{Nothing}) at /usr/local/Miniconda3-4.5.12-Linux-x86_64/envs/c3s-magic/lib/R/library/JuliaCall/julia/setup.jl:168
Execution halted
Julia exit.
```

Is there an installation step missing?

## Environment

* c3s-magic-wps version used, if any:
* Python version, if any:
* Operating System:

**Comment by jhardenberg** [comment]
Hi, that's strange. Did `esmvaltool/install/Julia/setup.jl` run ?

**Comment by cehbrecht** [comment]
Yes, I installed like describe in the `Dockerfile`:
```
c3s-magic) [root@cp4cds-cn2 Julia]# julia setup.jl 
┌ Info: Installing the packages from
└   scriptDir * "/julia_requirements.txt" = "/usr/local/Miniconda3-4.5.12-Linux-x86_64/envs/c3s-magic/lib/python3.6/site-packages/esmvaltool/install/Julia/julia_requirements.txt"
┌ Info: Installing
└   pkgName = "ArgParse"
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.0/Manifest.toml`
[...]
```

It has configs in `~/.julia`. The service is run by a different user then the installation. Are these configs needed and can put them somewhere else to be found (`/etc`)?

**Comment by jhardenberg** [comment]
> The service is run by a different user then the installation. Are these configs needed and can I put them somewhere else to be found (`/etc`)?

Aha, that is probably the problem. The installation step installs julia packages privately in the user home directory in `.julia`. If then another user wants to use it, he/she will not have the packages installed by `setup.jl` available.
By investigating this it seems that the desired package repository can be specified setting the `JULIA_DEPOT_PATH` environment variable before calling julia. So when installing you could do
```
JULIA_DEPOT_PATH=/path/to/shared/dir julia ./setup.jl
```
and then the user would need a `export  JULIA_DEPOT_PATH=/path/to/shared/dir`  in his/her environment ...
It seemed to work when I tried it ...

**Comment by cehbrecht** [comment]
I'm using now:
```
export JULIA_DEPOT_PATH=/usr/local/share/julia
```

But there is still an issue:
```
Julia version 1.0.3 at location /usr/local/src/julia-1.0.3/bin will be used.
Loading setup script for JuliaCall...
LoadError("/usr/local/Miniconda3-4.5.12-Linux-x86_64/envs/c3s-magic/lib/R/library/JuliaCall/julia/setup.jl", 63, SystemError("opening file /usr/local/share/julia/compiled/v1.0/Suppressor/1JN4R.ji", 13, nothing)) Error in .julia$cmd(paste0("Base.include(Main,\"", system.file("julia/setup.jl",  : 
  Error happens when you try to execute command Base.include(Main,"/usr/local/Miniconda3-4.5.12-Linux-x86_64/envs/c3s-magic/lib/R/library/JuliaCall/julia/setup.jl") in Julia.
                        To have more helpful error messages,
                        you could considering running the command in Julia directly
Calls: julia_setup -> <Anonymous>
In addition: Warning message:
In system2(file.path(.julia$bin_dir, "julia"), shQuote(command),  :
  running command ''/usr/local/src/julia-1.0.3/bin/julia' '--startup-file=no' '/usr/local/Miniconda3-4.5.12-Linux-x86_64/envs/c3s-magic/lib/R/library/JuliaCall/julia/install_dependency.jl' '/usr/local/anaconda/envs/c3s-magic/lib/R' 2>&1' had status 1
Execution halted
Julia exit.
```

**Comment by jhardenberg** [comment]
Ok, what happens if you change that to 
`export JULIA_DEPOT_PATH=/usr/local/share/julia:$HOME/.julia`
??? (sorry, at the moment I cannot test it directly myself)

**Comment by nielsdrost** [comment]
Switching to the ESMValtool conda package (#84) should help.

Also note that there is only a single Julia metric in the WPS, so consider focussing in the other metrics first.

**Comment by nielsdrost** [comment]
#84 done, assuming it fixes this issue.
